function clicaLite(){
    $('#porni').hide(300);
    $('#corni').hide(300,function(){
      $('#pfoto').hide(300);
      $('#cfoto').hide(300,function(){
        $('#pcine').hide(300);
        $('#ccine').hide(300,function(){
          $('#plite').animate({
            'height':'95vh',
            'top':'6%'
          },function(){
              $('#cl2').fadeIn('slow');
          });
        });
      });
    });
    $('#clite').fadeOut('slow');
    $('.cinema').animate({
      backgroundColor:'gray',
      'top':c1
    });
    $('.fotografia').animate({
      backgroundColor:'gray',
      'top':c2
    });
    $('.ornitologia').animate({
      backgroundColor:'gray',
      'top':c3
    });
    $('.literatura').animate({
      backgroundColor:'#000000',
      'top':c4
    });
    $('.ambit').animate({
      backgroundColor:'#EEC41B'
    },function(){
      $('.text').addClass('groc');
      $('.text p').html(tlite);
      $('.text').show('slow');
    });
    $('#go').attr('href','registre.php?a=lite');
}
function clicaCine(){
    $('#porni').hide(300);
    $('#corni').hide(300,function(){
      $('#pfoto').hide(300);
      $('#cfoto').hide(300,function(){
        $('#plite').hide(300);
        $('#clite').hide(300,function(){
          $('#pcine').animate({
            'height':'95vh',
            'top':'6%',
            'right':'12%'
          },function(){
              $('#cc2').fadeIn('slow');
          });
        });
      });
    });
    $('#ccine').fadeOut('slow');
    $('.cinema').animate({
      backgroundColor:'black',
      'top':c4
    });
    $('.fotografia').animate({
      backgroundColor:'gray',
      'top':c2
    });
    $('.ornitologia').animate({
      backgroundColor:'gray',
      'top':c3
    });
    $('.literatura').animate({
      backgroundColor:'gray'
    });
    $('.ambit').animate({
      backgroundColor:'#66A8C8'
    },function(){
      $('.text').addClass('blau');
      $('.text p').html(tcine);
      $('.text').show('slow');
    });
    
    $('#go').attr('href','registre.php?a=cine');
}
function clicaFoto(){
    $('#porni').hide(300);
    $('#corni').hide(300,function(){
      $('#pcine').hide(300);
      $('#ccine').hide(300,function(){
        $('#plite').hide(300);
        $('#clite').hide(300,function(){
          $('#pfoto').animate({
            'height':'95vh',
            'top':'6%',
            'right':'12%'
          },function(){
              $('#cf2').fadeIn('slow');
          });
        });
      });
    });
    $('#cfoto').fadeOut('slow');
    $('.cinema').animate({
      backgroundColor:'gray'
    });
    $('.fotografia').animate({
      backgroundColor:'black',
      'top':c4
    });
    $('.ornitologia').animate({
      backgroundColor:'gray',
      'top':c3
    });
    $('.literatura').animate({
      backgroundColor:'gray'
    });
    $('.ambit').animate({
      backgroundColor:'#F15D42'
    },function(){
      $('.text').addClass('roig');
      $('.text p').html(tfoto);
      $('.text').show('slow');
    });
    
    $('#go').attr('href','registre.php?a=foto');
}
function clicaOrni(){
    $('#pfoto').hide(300);
    $('#cfoto').hide(300,function(){
      $('#pcine').hide(300);
      $('#ccine').hide(300,function(){
        $('#plite').hide(300);
        $('#clite').hide(300,function(){
          $('#porni').animate({
            'height':'95vh',
            'top':'6%',
            'right':'12%'
          },function(){
              $('#co2').fadeIn('slow');
          });
        });
      });
    });
    $('#corni').fadeOut('slow');
    $('.cinema').animate({
      backgroundColor:'gray'
    });
    $('.fotografia').animate({
      backgroundColor:'gray'
    });
    $('.ornitologia').animate({
      backgroundColor:'black'
    });
    $('.literatura').animate({
      backgroundColor:'gray'
    });
    $('.ambit').animate({
      backgroundColor:'#ABB057'
    },function(){
      $('.text').addClass('verd');
      $('.text p').html(torni);
      $('.text').show('slow');
    });
    $('#go').attr('href','registre.php?a=orni');
}